#ifndef GLOBALOPTIONS_H_INCLUDED
#define GLOBALOPTIONS_H_INCLUDED

#define INFO_MESSAGES true
#define DEBUG_MESSAGES true
#define DEV_MESSAGES true

#include "Logger.h"

#endif // GLOBALOPTIONS_H_INCLUDED
